# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RamnLxJTLQCAG8sjuuUZjTfmvP_znYqN

# Support Vector Machine (SVM) for Cat and Dog Image Classification

## 1. Load and Preprocess Images

We need to load the images from the `train` directory, resize them to a fixed dimension, and convert them into a format that an SVM can process (e.g., a flattened pixel array). We'll also extract the labels (cat or dog) from the filenames.
"""

import os

# Ensure TRAIN_DIR is defined, using the same definition as in cell 7478eacf and 5bc89a57
TRAIN_DIR = '/content/dogs-vs-cats/train'

print(f"Verifying dataset directory: {TRAIN_DIR}")
if os.path.exists(TRAIN_DIR):
    print(f"Directory '{TRAIN_DIR}' exists.")
    files_in_dir = os.listdir(TRAIN_DIR)
    if files_in_dir:
        print(f"Found {len(files_in_dir)} items (files/folders) in '{TRAIN_DIR}'. Showing first 5: {files_in_dir[:5]}")
        print("\nAction: The dataset appears to be present. You can now proceed to re-run cell `7478eacf` to load and preprocess the images.")
    else:
        print(f"Directory '{TRAIN_DIR}' is empty.")
        print("\nAction: The directory is empty. Please ensure you re-run cell `4ade0ad5` (Download and Unzip the Dataset) to populate this directory with image files.")
elif not os.path.exists('/content/dogs-vs-cats'):
    print("Base directory '/content/dogs-vs-cats' does not exist.")
    print("\nAction: The base dataset directory is missing. Please ensure you re-run cell `4ade0ad5` (Download and Unzip the Dataset) to create the base directory and extract the dataset.")
else:
    print(f"Directory '{TRAIN_DIR}' does not exist, even though '/content/dogs-vs-cats' exists.")
    print("\nAction: The 'train' subdirectory is missing. Please ensure you re-run cell `4ade0ad5` (Download and Unzip the Dataset) to extract the 'train' folder correctly into '/content/dogs-vs-cats'.")

import os
import cv2 # OpenCV for image processing
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Define the path to the training images
TRAIN_DIR = '/content/dogs-vs-cats/train'
IMAGE_SIZE = 64 # Resize images to 64x64 pixels

def load_and_preprocess_images(data_dir, image_size):
    images = []
    labels = [] # 0 for cat, 1 for dog

    for filename in os.listdir(data_dir):
        if filename.endswith('.jpg'):
            # Determine label from filename
            if 'cat' in filename:
                label = 0
            elif 'dog' in filename:
                label = 1
            else:
                continue # Skip files not clearly labeled cat/dog

            img_path = os.path.join(data_dir, filename)
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE) # Read as grayscale for simplicity

            if img is not None:
                img = cv2.resize(img, (image_size, image_size))
                # Flatten the image into a 1D array
                images.append(img.flatten())
                labels.append(label)
            else:
                print(f"Warning: Could not read image {img_path}")

    return np.array(images), np.array(labels)

print(f"Loading and preprocessing images from {TRAIN_DIR}...")
X, y = load_and_preprocess_images(TRAIN_DIR, IMAGE_SIZE)

print(f"Loaded {len(X)} images with shape {X.shape}")
print(f"Loaded {len(y)} labels: {np.unique(y, return_counts=True)}")

"""### Verify Dataset Extraction

Let's check the contents of the `TRAIN_DIR` to confirm if the images have been extracted successfully after resolving the Kaggle authentication issue.
"""

print(f"Contents of {TRAIN_DIR} (first 10 files):")
!ls -1 "{TRAIN_DIR}" | head -10

# Count the number of files to ensure it's not empty
num_files = len(os.listdir(TRAIN_DIR))
print(f"Total files in {TRAIN_DIR}: {num_files}")

if num_files > 0:
    print("It appears files are now present in the training directory. You can proceed with running cell 7478eacf again, followed by the rest of the notebook.")
else:
    print("No files found in the training directory. Please re-check the Kaggle authentication (cell eddafecf) and dataset download/unzip (cell 4ade0ad5).")

"""## Re-downloading Kaggle Dataset

It seems the dataset was not found. Let's re-run the steps to ensure the 'dogs-vs-cats' dataset is correctly downloaded and extracted.

### Upload your Kaggle API key (if you haven't already or if it was cleared)

If your Kaggle API key (`kaggle.json`) is no longer present, please upload it again. You can do this by clicking the 'Files' icon on the left sidebar, then 'Upload to session storage' icon, and selecting the `kaggle.json` file. Alternatively, run the cell below:
"""

from google.colab import files

# Ensure the .kaggle directory exists
!mkdir -p ~/.kaggle

# Upload kaggle.json
try:
    uploaded = files.upload()
    for fn in uploaded.keys():
        print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')
        # Move kaggle.json to the correct directory
        !mv "{fn}" ~/.kaggle/kaggle.json
    !chmod 600 ~/.kaggle/kaggle.json # Set permissions
    print("Kaggle API key uploaded and configured successfully.")
except Exception as e:
    print(f"An error occurred during file upload or configuration: {e}")
    print("Please ensure you have downloaded 'kaggle.json' from your Kaggle account and try again.")

# This cell will configure your Kaggle API key using the already uploaded `kaggle.json`.
# It moves the uploaded kaggle.json to the correct directory (~/.kaggle/) and sets appropriate permissions.

from google.colab import files
import os

# Ensure the .kaggle directory exists
!mkdir -p ~/.kaggle

# Check if kaggle.json is in the current working directory from an earlier upload
if os.path.exists('/content/kaggle.json'):
    print("kaggle.json found in /content/. Moving it to ~/.kaggle/")
    !mv /content/kaggle.json ~/.kaggle/kaggle.json
    !chmod 600 ~/.kaggle/kaggle.json # Set permissions
    print("Kaggle API key configured successfully.")
else:
    print("kaggle.json not found in /content/. Please ensure it has been uploaded.")

"""### Download and Unzip the Dataset

Now, let's download and extract the dataset. This might take a few minutes.
"""

import os

# Download the Dogs vs. Cats dataset
# This assumes Kaggle API key is already configured (e.g., in ~/.kaggle/kaggle.json)
!kaggle competitions download -c dogs-vs-cats -p /content/

# Ensure the base directory exists
if not os.path.exists('/content/dogs-vs-cats'):
    !mkdir -p /content/dogs-vs-cats

# Unzip the main dogs-vs-cats.zip file into its designated folder
# This will place train.zip, test1.zip, and sampleSubmission.csv into /content/dogs-vs-cats/
!unzip -o -q /content/dogs-vs-cats.zip -d /content/dogs-vs-cats

# Now, unzip train.zip and test1.zip. The -d option specifies the *destination directory*.
# If train.zip contains a folder 'train/' with images inside, unzipping it to /content/dogs-vs-cats/
# will correctly place the 'train/' folder (and its contents) directly under /content/dogs-vs-cats/.
# This ensures the images are at /content/dogs-vs-cats/train/image_name.jpg

# Create the target directories if they don't exist (though unzip might create them)
if not os.path.exists('/content/dogs-vs-cats/train'):
    !mkdir -p /content/dogs-vs-cats/train
!unzip -o -q /content/dogs-vs-cats/train.zip -d /content/dogs-vs-cats/

if not os.path.exists('/content/dogs-vs-cats/test1'):
    !mkdir -p /content/dogs-vs-cats/test1
!unzip -o -q /content/dogs-vs-cats/test1.zip -d /content/dogs-vs-cats/

print("Dataset downloaded and unzipped successfully!")

# Verify content in the extracted train and test directories
print("Contents of /content/dogs-vs-cats/train/ (first 5):")
!ls /content/dogs-vs-cats/train | head -5
print("\nContents of /content/dogs-vs-cats/test1/ (first 5):")
!ls /content/dogs-vs-cats/test1 | head -5

# After this, you should be able to re-run the image loading cell (7478eacf) and subsequent cells.

# This cell will download and unzip the Dogs vs. Cats dataset.
# This should create the missing `/content/dogs-vs-cats/train` directory.

import os

# Download the Dogs vs. Cats dataset
# This assumes Kaggle API key is already configured (e.g., in ~/.kaggle/kaggle.json)
!kaggle competitions download -c dogs-vs-cats -p /content/

# Ensure the base directory exists
if not os.path.exists('/content/dogs-vs-cats'):
    !mkdir -p /content/dogs-vs-cats

# Unzip the main dogs-vs-cats.zip file into its designated folder
# This will place train.zip, test1.zip, and sampleSubmission.csv into /content/dogs-vs-cats/
!unzip -o -q /content/dogs-vs-cats.zip -d /content/dogs-vs-cats

# Now, unzip train.zip and test1.zip. The -d option specifies the *destination directory*.
# If train.zip contains a folder 'train/' with images inside, unzipping it to /content/dogs-vs-cats/
# will correctly place the 'train/' folder (and its contents) directly under /content/dogs-vs-cats/.
# This ensures the images are at /content/dogs-vs-cats/train/image_name.jpg

# Create the target directories if they don't exist (though unzip might create them)
if not os.path.exists('/content/dogs-vs-cats/train'):
    !mkdir -p /content/dogs-vs-cats/train
!unzip -o -q /content/dogs-vs-cats/train.zip -d /content/dogs-vs-cats/

if not os.path.exists('/content/dogs-vs-cats/test1'):
    !mkdir -p /content/dogs-vs-cats/test1
!unzip -o -q /content/dogs-vs-cats/test1.zip -d /content/dogs-vs-cats/

print("Dataset downloaded and unzipped successfully!")

# Verify content in the extracted train and test directories
print("Contents of /content/dogs-vs-cats/train/ (first 5):")
!ls /content/dogs-vs-cats/train | head -5
print("\nContents of /content/dogs-vs-cats/test1/ (first 5):")
!ls /content/dogs-vs-cats/test1 | head -5

print("\nAfter running this cell, you should now be able to re-run cell `7478eacf` to load and preprocess the images.")

"""## 2. Split Data into Training and Testing Sets

To evaluate our model effectively, we'll split the preprocessed data into training and testing sets. This ensures that the model is tested on unseen data.
"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Training data shape: {X_train.shape}")
print(f"Testing data shape: {X_test.shape}")
print(f"Training labels distribution: {np.unique(y_train, return_counts=True)}")
print(f"Testing labels distribution: {np.unique(y_test, return_counts=True)}")

def load_and_preprocess_images(data_dir, image_size):
    images = []
    labels = [] # 0 for cat, 1 for dog

    for filename in os.listdir(data_dir):
        if filename.endswith('.jpg'):
            # Determine label from filename
            if 'cat' in filename:
                label = 0
            elif 'dog' in filename:
                label = 1
            else:
                continue # Skip files not clearly labeled cat/dog

            img_path = os.path.join(data_dir, filename)
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE) # Read as grayscale for simplicity

            if img is not None:
                img = cv2.resize(img, (image_size, image_size))
                # Flatten the image into a 1D array
                images.append(img.flatten())
                labels.append(label)
            else:
                print(f"Warning: Could not read image {img_path}")

    return np.array(images), np.array(labels)

print(f"Loading and preprocessing images from {TRAIN_DIR}...")
X, y = load_and_preprocess_images(TRAIN_DIR, IMAGE_SIZE)

print(f"Loaded {len(X)} images with shape {X.shape}")
print(f"Loaded {len(y)} labels: {np.unique(y, return_counts=True)}")

"""## 3. Train the Support Vector Machine (SVM) Classifier

Now we'll train a Support Vector Machine (SVC) classifier using the training data. For image classification, SVMs are a classic choice, especially when combined with appropriate feature extraction. We'll use a linear kernel for simplicity, but more complex kernels (like RBF) could also be explored.
"""

print("Training SVM classifier...")
# Initialize SVM classifier (SVC with default parameters, which is RBF kernel)
# For simplicity and faster training, we can start with a linear kernel
svm_model = SVC(kernel='linear', random_state=42, verbose=True)

# Train the model
svm_model.fit(X_train, y_train)

print("SVM training complete.")

import pandas as pd

csv_file_path = '/content/sampleSubmission.csv'

# Read the CSV file into a pandas DataFrame
df_csv = pd.read_csv(csv_file_path)

# Convert the DataFrame to a JSON string
json_output = df_csv.to_json(orient='records', indent=4)

print("CSV content converted to JSON:")
print(json_output)

import pandas as pd

csv_file_path = '/content/sampleSubmission.csv'

# Read the CSV file into a pandas DataFrame
df_csv = pd.read_csv(csv_file_path)

# Convert the DataFrame to a JSON string
json_output = df_csv.to_json(orient='records', indent=4)

# Define the output file path
output_json_file = 'output.json'

# Write the JSON string to a file
with open(output_json_file, 'w') as f:
    f.write(json_output)

print(f"JSON output successfully saved to {output_json_file}")

import os

# List the contents of the /content/ directory to verify file presence
print("Contents of /content/ directory:")
!ls -F /content/

"""If `sampleSubmission.csv` is not listed above, please upload it to the `/content/` directory. Once you've confirmed the file is present, let's try to read it again."""

import pandas as pd

csv_file_path = '/content/sampleSubmission.csv'

# Check if the file exists before attempting to read
if os.path.exists(csv_file_path):
    print(f"File '{csv_file_path}' found. Attempting to read...")
    # Read the CSV file into a pandas DataFrame
    df_csv_recheck = pd.read_csv(csv_file_path)

    # Convert the DataFrame to a JSON string
    json_output_recheck = df_csv_recheck.to_json(orient='records', indent=4)

    print("CSV content re-converted to JSON (recheck):")
    print(json_output_recheck)

    # Optionally save it again
    output_json_file_recheck = 'output_recheck.json'
    with open(output_json_file_recheck, 'w') as f:
        f.write(json_output_recheck)
    print(f"JSON output successfully saved to {output_json_file_recheck}")
else:
    print(f"File '{csv_file_path}' still not found. Please ensure it's uploaded to /content/.")

print("Contents of /content/ directory:")
!ls -F /content/

"""## 4. Evaluate the SVM Model

After training, we'll evaluate the SVM's performance on the unseen test data. We'll look at the accuracy score and a classification report for more detailed metrics like precision, recall, and F1-score.
"""

TRAIN_DIR = '/content/dogs-vs-cats/train'
IMAGE_SIZE = 64 # Resize images to 64x64 pixels

print(f"TRAIN_DIR set to: {TRAIN_DIR}")
print(f"IMAGE_SIZE set to: {IMAGE_SIZE}")

print("Evaluating SVM model...")

# Make predictions on the test set
y_pred = svm_model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# Display classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['cat', 'dog']))